import '../src/app/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  themeColor: '#000000',
  manifest: '/manifest.json',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <head>
        {/* Etiquetas adicionales para Apple */}
        <meta name="background-color" content="#ffffff" />
        <link rel="apple-touch-icon" href="/icons/icon-192x192.png" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="MiApp" />
      </head>
      <body className="fondo">{children}</body>
    </html>
  )
}
