import '../../src/app/globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div> 
           <body className='fondo' >{children}</body>
  </div>
  )
}