// ❌ No pongas "use client" aquí
import '../../src/app/globals.css'

// ✅ metadata SÍ puede estar aquí
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className="fondo">
        {children}
      </body>
    </html>
  )
}
